USE GD1C2019
GO

-- Verifico si existe el schema, si no existe lo creo

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'ICE_CUBES')
	BEGIN
		EXEC sys.sp_executesql N'CREATE SCHEMA [ICE_CUBES] AUTHORIZATION [gdCruceros2019]'
		--PRINT 'Schema correctamente creado'
	END
GO

/************************** INI-BORRADO DE TABLAS***************************/

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ICE_CUBES.Rol'))
	DROP TABLE ICE_CUBES.Rol

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ICE_CUBES.Funcionalidad'))
	DROP TABLE ICE_CUBES.Funcionalidad

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ICE_CUBES.Rol_Funcionalidad'))
	DROP TABLE ICE_CUBES.Rol_Funcionalidad

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ICE_CUBES.USUARIO'))
	DROP TABLE ICE_CUBES.USUARIO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ICE_CUBES.CLIENTE'))
	DROP TABLE ICE_CUBES.CLIENTE

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ICE_CUBES.COMPRA'))
	DROP TABLE ICE_CUBES.COMPRA
	
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ICE_CUBES.RESERVA'))
	DROP TABLE ICE_CUBES.RESERVA
	
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ICE_CUBES.PUERTO'))
	DROP TABLE ICE_CUBES.PUERTO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ICE_CUBES.CRUCERO'))
	DROP TABLE ICE_CUBES.CRUCERO
	
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ICE_CUBES.RECORRIDO'))
	DROP TABLE ICE_CUBES.RECORRIDO
	
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ICE_CUBES.TRAMO_SIMPLE'))
	DROP TABLE ICE_CUBES.TRAMO_SIMPLE
	
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ICE_CUBES.TRAMO_COMPUESTO'))
	DROP TABLE ICE_CUBES.TRAMO_COMPUESTO
	
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ICE_CUBES.CABINA'))
	DROP TABLE ICE_CUBES.CABINA
	
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ICE_CUBES.TIPO_CABINA'))
	DROP TABLE ICE_CUBES.TIPO_CABINA
	
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ICE_CUBES.VIAJE'))
	DROP TABLE ICE_CUBES.VIAJE
	
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ICE_CUBES.PASAJE'))
	DROP TABLE ICE_CUBES.PASAJE

/************************** FIN-BORRADO DE TABLAS***************************/




/************************** INI-CREACION DE TABLAS***************************/
CREATE TABLE ICE_CUBES.Rol (
	ROL_ID NUMERIC(18,0) IDENTITY(1,1) NOT NULL,
	ROL_DESCRIPCION NVARCHAR(255) NOT NULL,
	ROL_ESTADO BIT NOT NULL DEFAULT 1, 
		PRIMARY KEY (ROL_ID)
)
GO

CREATE TABLE ICE_CUBES.Funcionalidad (
	FUNCION_ID NUMERIC(18,0) IDENTITY(1,1) NOT NULL,
	FUNCION_NOMBRE NVARCHAR(255) NOT NULL,
		PRIMARY KEY (FUNCION_ID)
)
GO

CREATE TABLE ICE_CUBES.Rol_Funcionalidad (
	--Rol_Funcionalidad_ID NUMERIC(18,0) IDENTITY(1,1),
	ID_rol NUMERIC(18,0) NOT NULL,
	ID_funcionalidad NUMERIC(18,0) NOT NULL,
	--	PRIMARY KEY(Rol_Funcionalidad_ID)
)	
GO
CREATE TABLE ICE_CUBES.USUARIO (
	USERDNI_ID DECIMAL(18,0) PRIMARY KEY NOT NULL,
	USER_TIPO CHAR (2) NOT NULL,
	USER_PASS NVARCHAR(255) NOT NULL,
	USER_ROL NUMERIC (18,0) NOT NULL,
	USER_ESTADO TINYINT	NOT NULL DEFAULT 0,
	USER_INTENTOS TINYINT NOT NULL DEFAULT 0,
	)
GO
CREATE TABLE iCE_CUBES.CLIENTE (
	CLIE_DNIID DECIMAL(18,0) PRIMARY KEY NOT NULL,
	CLIE_NOMBRE NVARCHAR(255) NOT NULL,
	CLIE_APELLIDO NVARCHAR(255) NOT NULL,
	CLI_DIR NVARCHAR(255) NOT NULL,
	CLI_TELEFONO INT,
	CLI_MAIL NVARCHAR(255),
	CLI_FECHA_NAC DATETIME2(3)
	)

GO

CREATE TABLE ICE_CUBES.COMPRA(
	COMPRA_ID INT IDENTITY(1,1) NOT NULL,
	COMPRA_RESERVA_ID DECIMAL(18,0),
	COMPRA_CLIENTE DECIMAL(18,0),
	)

GO

CREATE TABLE ICE_CUBES.RESERVA ( 
	RESERVA_ID INT IDENTITY(1,1) NOT NULL,
	RESERVA_FECHA DATETIME2(3) NOT NULL,
	RESERVA_CLIENTE DECIMAL (18,0)
)	
GO

CREATE TABLE ICE_CUBES.PUERTO(
	PUERTO_ID INT IDENTITY(1,1) NOT NULL,
	PUERTO_NOMBRE NVARCHAR(255),
	PUERTO_ESTADO BIT NOT NULL
	)

GO
CREATE TABLE ICE_CUBES.RECORRIDO(
	RECO_ID INT NOT NULL,
	RECO_TIPO CHAR (1) NOT NULL,
	RECO_ESTADO BIT NOT NULL,  
)

GO

CREATE TABLE ICE_CUBES.TRAMO_SIMPLE (
	SIMP_RECO_ID INT NOT NULL,
	SIMP_ORIGEN INT,
	SIMP_DESTINO INT,
	SIMP_PRECIO DECIMAL (18,2)
)
	

GO

CREATE TABLE ICE_CUBES.TRAMO_COMPUESTO (
	COMP_RECO_ID INT NOT NULL,
	COMP_SIMPLE INT )
	
GO

CREATE TABLE ICE_CUBES.CRUCERO (
	CRUCERO_ID INT IDENTITY (1,1) NOT NULL,
	CRUCERO_MODELO NVARCHAR(50),
	CRUCERO_IDENTIFICADOR  NVARCHAR(50),
	CRUCERO_MARCA NVARCHAR(255),
	CRUERO_TIPO_SERVICIO NVARCHAR(50),
	CRUCERO_ESTADO BIT ,
	CRUCERO_FALTA DATETIME2(3),
	CRUCERO_FFUERA_SERVICIO DATETIME2(3),
	CRUCERO_FREINICIO DATETIME2(3),
	CRUCERO_BAJA_DEF DATETIME2(3),
)

GO

CREATE TABLE ICE_CUBES.CABINA(
	CABINA_ID INT IDENTITY(1,1) NOT NULL,
	CABINA_CRUCERO_ID INT, --FK CRUCERO
	CABINA_PISO DECIMAL(18,0),
	CABINA_NUMERO DECIMAL (18,0),
	CABINA_TIPO INT --FK TIPO CABINA
	)

GO

CREATE TABLE ICE_CUBES.TIPO_CABINA(
	TIPO_CABINA INT IDENTITY(1,1) NOT NULL,
	TIPO_NOMBRE NVARCHAR (50)
	)
	
GO 

CREATE TABLE ICE_CUBES.VIAJE (
	VIAJE_ID INT IDENTITY (1,1),
	VIAJE_CRUCERO_ID INT,--FK CRUCERO
	VIAJE_RECORRIDO_ID INT, -- FK RECORRIDO
	VIAJE_FINICIO DATETIME,
	VIAJE_FFIN DATETIME
)

GO

CREATE TABLE ICE_CUBES.PASAJE(
	PASAJE_VIAJE_ID INT, --PK/FK VIAJE
	PASAJE_CABINA_ID INT, -- PK/FK CABINA
	PASAJE_PRECIO DECIMAL (18,2),
	PASAJE_COMPRA_ID INT, --FK COMPRA
	PASAJE_RESERVA_ID INT, --FK RESERVA
	)

GO

/************************** FIN-CREACION DE TABLAS***************************/